### PR TITLE
B2B-1354: [update] fix s2s endpoints review issues

### PR DESCRIPTION
**Pull request by JamessenLiu**
# [B2B-1354](https://bigcommercecloud.atlassian.net/browse/B2B-1354)

### Fix some issues
Fix s2s endpoints issues in [google doc](https://docs.google.com/document/d/1maGQinFAxBQH8b3h0EGwzUZi9ikpf-mAgTWgVLqGo4I/edit?usp=sharing)
* company
    a. Bulk Create Companies (request body has these additional read only fields (bcGroupName and companyStatus)
     **Create a new model for bulk company create (copy from orrigin), and remove 2 read only fields**

* User
    a. Get a User (companyRoleId and companyRoleName missing from response body)
    **Add companyRoleName and companyRoleId in user response model**
   
    b. Get a User (meta is missing from the 404 error response)
    **Fix 404 response**

    c. Get a User (Should we document a 500 error response?)
    **Remove 500 response**

   d. Update a User (companyRoleId and companyRoleName are not in response body)
    **Add companyRoleName and companyRoleId in user response model**
    
    e. Delete a User  (meta is missing from the 404 error response)
    **Fix 404 response**

    f. Delete a User (Should we document a 500 error response?)
    **Remove 500 response**

    g. Get Users (companyRoleId and companyRoleName missing from response body)
     **Add companyRoleName and companyRoleId in user response model**

    i. Bulk Create Company User (meta is missing from the 404 error response)
     **Fix 404 response**

    j. Get a User by Customer ID (companyRoleId and companyRoleName missing from response body)
    **Add companyRoleName and companyRoleId in user response model**

    k. Get a User by Customer ID (meta is missing from the 404 error response)
    **Fix 404 response**

* Sales Staff
    a. Get a Sales Staff (assignedAt field is missing from the response body > assignedCompanies)
    **Add assignAt**

* invoice payment
    a. Update a Offline Payment (422 error response is this correct? Data > currency)
    **Fix 422 response**

### Remove task section
The task section has been removed in PR [535](https://github.com/bigcommerce/docs/pull/535), but re-created in PR [562](https://github.com/bigcommerce/docs/pull/562). May be conflicts between PR. As  this section has already been removed in the original Stoplight, it should be removed again.
    

## Release notes draft

n/a

[B2B-1354]: https://bigcommercecloud.atlassian.net/browse/B2B-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JamessenLiu** [comment]
Hi, @bc-traciporter 
Please review. 
The task section should be removed from docs. If the nav menu also need to be updated, can you help to do this? Thank
image

**Comment by bc-traciporter** [comment]
Hi @JamessenLiu Thank you so much for your help. I removed the task menu item in [PR 1024](https://github.com/bigcommerce/developer-center/pull/1024).

**Review by bc-traciporter — APPROVED** [review]
LGTM

**Comment by JamessenLiu** [comment]
Hi, @bc-traciporter 
I think we should keep the channel section in the navigation menu and list it in the Management APIs. Here is a screenshot from Stoplight.
image

**Comment by bc-traciporter** [comment]
Thank you @JamessenLiu Channel has been added. I re-arranged the list so that they both matched and they are in alphabetical order.

**Pull request merged**
