### PR TITLE
Issue-512

### PR DESCRIPTION
**Pull request by bc-traciporter**
# [Issue-512](https://github.com/bigcommerce/docs/issues/512)

## What changed?
Updated description for subtotal_ex_tax

## Release notes draft
Bug Fix, see Issue-512

* 

## Anything else?

ping {names}

### CODE REVIEW

**Comment by WillemHoman** [comment]
Thanks for following up with this @bc-traciporter.

We should probably document this for the other prices which can't be negative at the same time.
I've omitted the readonly fields like `subtotal_tax` as this is derived from `subtotal_inc_tax - subtotal_ex_tax` and they can be negative if ex > inc.

### Order fields
- subtotal_ex_tax
- subtotal_inc_tax
- base_shipping_cost
- shipping_cost_ex_tax
- shipping_cost_inc_tax
- base_handling_cost
- handling_cost_ex_tax
- handling_cost_inc_tax
- base_wrapping_cost
- wrapping_cost_ex_tax
- wrapping_cost_inc_tax
- total_ex_tax
- total_inc_tax
- refunded_amount
- discount_amount

### Product fields
- price_inc_tax
- price_ex_tax
- wrapping_cost_inc_tax
- wrapping_cost_ex_tax
- weight
- width
- depth
- height
- cost_price_inc_tax
- cost_price_ex_tax

**Comment by cjbarth** [comment]
That is a lot of places, and several of those illustrates my comment here: https://github.com/bigcommerce/docs/issues/512#issuecomment-2354366621

**Comment by bc-traciporter** [comment]
Hi @WillemHoman I updated the remaining fields.

**Review by WillemHoman — APPROVED** [review]
Thanks @bc-traciporter

**Review by bc-andreadao — APPROVED** [review]

**Pull request merged**
