### PR TITLE
DEVDOCS-5908: [update] update request to add a price adjuster

### PR DESCRIPTION
**Pull request by bc-traciporter**
# [DEVDOCS-5908]

## What changed?
Updated request to add a price adjuster

## Release notes draft

Bug Fix

* 

## Anything else?

ping {names}

[DEVDOCS-5908]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CNanninga — APPROVED** [review]
This looks correct to me.

**Comment by bc-traciporter** [comment]
I would like to go ahead and merge this PR because the source file is correct. The issue was that it did not render correctly. However, [SELDEV-624](https://bigcommercecloud.atlassian.net/browse/SELFDEV-624) is showing as closed so I think the problem has been fixed. @bigcommerce/team-catalog-ops can you approve?

**Comment by mykhailo-banin** [comment]
Hey
May I ask to remove my email from this rep notifications
Thanks in advance

**Review by olysenko — APPROVED** [review]

**Comment by bc-traciporter** [comment]
HI @olysenko can you remove @mykhailo-banin from the team-catalog-ops notification?

**Pull request merged**
