### PR TITLE
B2B-1322: [update] remove old version extra fields

### PR DESCRIPTION
**Pull request by JamessenLiu**
# [B2B-1322](https://bigcommercecloud.atlassian.net/browse/B2B-1322)

## What changed?

The old version of extra fields is now hardly used by any merchants, so it is necessary to remove the relevant fields and descriptions from the B2B Edition documentation.
* Remove old version extra fields, Including extraInt, extraStr, etc；
* Added descriptions of the new version of extraFields to some documents, which were missing in the current documentation.

## Release notes draft

N/A

## Anything else?

ping {names}

[B2B-1322]: https://bigcommercecloud.atlassian.net/browse/B2B-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by bc-traciporter** [comment]
Hi @JamessenLiu will these changes effect these fields in b2b storefront orders.  Today, I created [PR 537](https://github.com/bigcommerce/docs/pull/537) for changes to orders. Do I need to remove these fields in this PR ?

**Review by bc-micah — APPROVED** [review]

**Comment by JamessenLiu** [comment]
> Hi @JamessenLiu will these changes effect these fields in b2b storefront orders. Today, I created https://github.com/bigcommerce/docs/pull/537 for changes to orders. Do I need to remove these fields in this PR ?

@bc-traciporter 
Although [pr-537](https://github.com/bigcommerce/docs/pull/537) and the current PR both modify storefront orders, their purposes are different, and they do not modify the same block of code. There should be no conflicts between them. You can merge your PR first, and if there really is a conflict, I will resolve it in this PR before merging.

**Comment by bc-traciporter** [comment]
@JamessenLiu great, that is good to know. I am waiting for approval and I wanted to find out why Get order's images is our docs, but not in stoplight. Then I can merge [PR 537](https://github.com/bigcommerce/docs/pull/537).

**Comment by JamessenLiu** [comment]
@bc-traciporter 
Get Order's Images is set as internal endpoint.  Therefore, it will not appear in the public B2B stoplight documentation unless you log into stoplight.
image
image

**Comment by bc-traciporter** [comment]
@JamessenLiu I have a quick question about these internal endpoints. There are two ways for us to hide them. They can be removed and put in a gated repository so approval is needed to view them or we can add the internal flag so the docs don't appear in the dev center but they would be accessible in GitHub.  
We need to understand how private and secure we should make these endpoints.

**Comment by JamessenLiu** [comment]
@bc-traciporter 
I think these internal documents can be removed directly, as these APIs are no longer in use in the B2B Edition.

**Pull request merged**
